--- 
language: scala
script: >
 sbt $COVERAGE ++$TRAVIS_SCALA_VERSION coverage test coverageReport &&
 sbt ++$TRAVIS_SCALA_VERSION test &&
 cd target &&
 git clone https://github.com/lemonlabsuk/scala-uri-demo.git &&
 cd scala-uri-demo &&
 sbt -Dscala.ver=$TRAVIS_SCALA_VERSION -Dscala.uri.ver=1.4.7 test &&
 cd "$TRAVIS_BUILD_DIR"

jdk:
  - oraclejdk8

matrix:
  include:
    - scala: 2.13.0
      env: COVERAGE=coverageOff
    - scala: 2.12.8
      env: COVERAGE=coverageOn
    - scala: 2.11.12
      env: COVERAGE=coverageOff

sudo: false # Enable new travis container-based infrastructure

after_success:
  - bash <(curl -s https://codecov.io/bash)
